### ISSUE TITLE
Need Solution in other languages except java. 

### ISSUE THREAD

**Issue by KhushalPShah** [TechnoBlogger14o3/HackerRank-Interview-Preparation-Kit-Solutions#2]
Hey!
I have solutions of the various sections inside the Interview Preparation Kit in C language.
Should I include them in this by raising a PR?
Since the repo has no solutions in C/C++, and it might be helpful for many people who prefer C/C++ (like me)

If yes, please let me know.
Else feel free to close this issue.

Cheers!

**Comment by TechnoBlogger14o3** [comment]
Absolutely.

**Comment by KhushalPShah** [comment]
Alright
I ll raise a PR in a while.

PS: Can you tag this issue with hacktoberfest?
It shall help me for my contributions. (I am a beginner)

Thanks!

**Comment by TechnoBlogger14o3** [comment]
Done.

**Comment by KhushalPShah** [comment]
@TechnoBlogger14o3 
There seems to be a typo in your label.
Please add : 
hacktoberfest-accepted
and 
hacktoberfest

Thanks and Cheers!

**Comment by Anamika810** [comment]
I want to work on this issue.

**Comment by TechnoBlogger14o3** [comment]
@Anamika810 
Then please do proceed and raise a PR at your convenience.

**Comment by nk183** [comment]
@TechnoBlogger14o3  can I work on this?

**Comment by TechnoBlogger14o3** [comment]
@nk183 Please do.

**Comment by nk183** [comment]
@TechnoBlogger14o3 ,what is the question ??

**Comment by TechnoBlogger14o3** [comment]
Thanks all for the contribution.
